export const WHATSAPP_URL = "https://wa.link/gme782";

export const SITE_NAME = "GorkhaBooks";
export const SITE_DOMAIN = "gorkha.com";
export const SITE_TAGLINE = "नेपालको #१ भरोसेमान्य गेमिङ र बेटिङ प्लेटफर्म";

export const NAV_LINKS = [
  { label: "Home", labelNe: "गृहपृष्ठ", href: "/" },
  { label: "Sports", labelNe: "स्पोर्ट्स", href: "/sports" },
  { label: "Live Casino", labelNe: "लाइभ क्यासिनो", href: "/casino" },
  { label: "Promotions", labelNe: "प्रमोसनहरू", href: "/promotions" },
  { label: "Blog", labelNe: "ब्लग", href: "/blog" },
  { label: "About", labelNe: "हाम्रोबारे", href: "/about" },
  { label: "Contact", labelNe: "सम्पर्क", href: "/contact" },
];

export const SPORTS = [
  {
    id: "cricket",
    name: "Cricket",
    icon: "🏏",
    matches: 24,
    live: 3,
    description: "IPL, World Cup, T20 & more",
    gradient: "from-emerald-500 to-green-700",
    image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=400&q=75",
  },
  {
    id: "football",
    name: "Football",
    icon: "⚽",
    matches: 38,
    live: 7,
    description: "Premier League, La Liga, Champions League",
    gradient: "from-blue-500 to-blue-800",
    image: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400&q=75",
  },
  {
    id: "tennis",
    name: "Tennis",
    icon: "🎾",
    matches: 16,
    live: 2,
    description: "Grand Slam, ATP, WTA Events",
    gradient: "from-yellow-500 to-orange-600",
    image: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=400&q=75",
  },
  {
    id: "esports",
    name: "Esports",
    icon: "🎮",
    matches: 12,
    live: 5,
    description: "BGMI, DOTA 2, CS2 & more",
    gradient: "from-purple-500 to-pink-700",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&q=75",
  },
  {
    id: "kabaddi",
    name: "Kabaddi",
    icon: "🤼",
    matches: 8,
    live: 1,
    description: "Pro Kabaddi League & Tournaments",
    gradient: "from-red-500 to-red-800",
    image: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=400&q=75",
  },
  {
    id: "basketball",
    name: "Basketball",
    icon: "🏀",
    matches: 14,
    live: 4,
    description: "NBA, EuroLeague & International",
    gradient: "from-orange-500 to-red-600",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&q=75",
  },
];

export const CASINO_GAMES = [
  {
    id: "roulette",
    name: "Live Roulette",
    type: "Live Dealer",
    players: 1240,
    minBet: "NPR 100",
    maxBet: "NPR 1,00,000",
    gradient: "from-red-600 to-red-900",
    badge: "HOT",
    emoji: "🎡",
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=75",
  },
  {
    id: "blackjack",
    name: "Blackjack VIP",
    type: "Live Dealer",
    players: 890,
    minBet: "NPR 200",
    maxBet: "NPR 2,00,000",
    gradient: "from-green-600 to-green-900",
    badge: "VIP",
    emoji: "🃏",
    image: "https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=600&q=75",
  },
  {
    id: "teenpatti",
    name: "Teen Patti",
    type: "Live Dealer",
    players: 3200,
    minBet: "NPR 50",
    maxBet: "NPR 50,000",
    gradient: "from-yellow-500 to-yellow-800",
    badge: "POPULAR",
    emoji: "🎴",
    image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&q=75",
  },
  {
    id: "slots",
    name: "Mega Slots",
    type: "Slots",
    players: 560,
    minBet: "NPR 10",
    maxBet: "NPR 10,000",
    gradient: "from-purple-600 to-purple-900",
    badge: "NEW",
    emoji: "🎰",
    image: "https://images.unsplash.com/photo-1596838132731-3301c3fd4317?w=600&q=75",
  },
  {
    id: "andarbahar",
    name: "Andar Bahar",
    type: "Live Dealer",
    players: 2100,
    minBet: "NPR 50",
    maxBet: "NPR 75,000",
    gradient: "from-pink-500 to-rose-800",
    badge: "TRENDING",
    emoji: "🀄",
    image: "https://images.unsplash.com/photo-1615631648086-325025c9e51e?w=600&q=75",
  },
  {
    id: "baccarat",
    name: "Baccarat Royal",
    type: "Live Dealer",
    players: 740,
    minBet: "NPR 500",
    maxBet: "NPR 5,00,000",
    gradient: "from-amber-500 to-yellow-700",
    badge: "VIP",
    emoji: "👑",
    image: "https://images.unsplash.com/photo-1571721795195-a2ca2d3370a9?w=600&q=75",
  },
];

export const PROMOTIONS = [
  {
    id: "welcome",
    title: "Welcome Bonus",
    subtitle: "100% First Deposit Bonus",
    amount: "Up to NPR 10,000",
    description: "Join GorkhaBooks today and get 100% match on your first deposit. Start winning big from day one!",
    badge: "NEW MEMBER",
    gradient: "from-yellow-400 to-yellow-600",
    expiry: "Limited Time",
    color: "gold",
  },
  {
    id: "cashback",
    title: "Weekly Cashback",
    subtitle: "10% Cashback Every Week",
    amount: "Up to NPR 5,000",
    description: "Never lose too much. Get 10% of your weekly losses back into your account every Monday.",
    badge: "WEEKLY",
    gradient: "from-green-400 to-emerald-600",
    expiry: "Every Monday",
    color: "green",
  },
  {
    id: "referral",
    title: "Refer & Earn",
    subtitle: "Earn for Every Friend",
    amount: "NPR 500 Per Referral",
    description: "Invite your friends to GorkhaBooks and earn NPR 500 for each friend who joins and deposits.",
    badge: "REFERRAL",
    gradient: "from-blue-400 to-blue-600",
    expiry: "No Expiry",
    color: "blue",
  },
  {
    id: "vip",
    title: "VIP Rewards",
    subtitle: "Exclusive VIP Program",
    amount: "Up to NPR 1,00,000",
    description: "Reach VIP status and unlock exclusive bonuses, faster withdrawals, and personal account manager.",
    badge: "VIP",
    gradient: "from-purple-400 to-purple-700",
    expiry: "Ongoing",
    color: "purple",
  },
  {
    id: "daily",
    title: "Daily Login Bonus",
    subtitle: "Login Everyday & Win",
    amount: "Up to NPR 2,000",
    description: "Login every day and collect your daily bonus. The streak gets bigger the longer you play!",
    badge: "DAILY",
    gradient: "from-orange-400 to-orange-600",
    expiry: "Daily",
    color: "orange",
  },
  {
    id: "reload",
    title: "Reload Bonus",
    subtitle: "50% on Every Deposit",
    amount: "Up to NPR 3,000",
    description: "Every reload earns you 50% bonus. Keep your bankroll healthy with our ongoing reload offers.",
    badge: "RELOAD",
    gradient: "from-rose-400 to-red-700",
    expiry: "Every Deposit",
    color: "red",
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Rajan Shrestha",
    location: "Kathmandu",
    avatar: "RS",
    rating: 5,
    text: "GorkhaBooks is the best! I withdrew NPR 45,000 within 10 minutes. Super fast and reliable. Best platform in Nepal!",
    amount: "Won NPR 45,000",
    game: "Cricket Betting",
  },
  {
    id: 2,
    name: "Sunita Tamang",
    location: "Pokhara",
    avatar: "ST",
    rating: 5,
    text: "Joined through WhatsApp and was playing within minutes. The Teen Patti live dealer is amazing. Highly recommend!",
    amount: "Won NPR 12,500",
    game: "Teen Patti",
  },
  {
    id: 3,
    name: "Bikash Rai",
    location: "Biratnagar",
    avatar: "BR",
    rating: 5,
    text: "I love the sports betting section. The odds are great and the platform is super easy to use. Support is top notch!",
    amount: "Won NPR 28,000",
    game: "Football Betting",
  },
  {
    id: 4,
    name: "Anita Gurung",
    location: "Chitwan",
    avatar: "AG",
    rating: 5,
    text: "The welcome bonus was amazing. Got NPR 5000 free on my first deposit. The VIP program is also very generous!",
    amount: "Won NPR 18,750",
    game: "Live Roulette",
  },
  {
    id: 5,
    name: "Pradip Magar",
    location: "Lalitpur",
    avatar: "PM",
    rating: 5,
    text: "Best customer support I have experienced. They reply on WhatsApp instantly. Withdrawals are always instant!",
    amount: "Won NPR 35,000",
    game: "IPL Betting",
  },
  {
    id: 6,
    name: "Kiran Karki",
    location: "Dharan",
    avatar: "KK",
    rating: 5,
    text: "Playing on GorkhaBooks for 6 months now. Consistent wins and amazing live casino. Highly trusted platform!",
    amount: "Won NPR 62,000",
    game: "Blackjack VIP",
  },
];

export const FAQS = [
  {
    question: "GorkhaBooks मा कसरी Join गर्ने? | How do I join GorkhaBooks?",
    answer: "Join गर्न एकदम सजिलो छ! जुनसुकै 'Join Now' बटन थिच्नुस् — तपाईं हाम्रो WhatsApp मा पुग्नुहुनेछ। हाम्रो टोलीले ५ मिनेटभित्र तपाईंको खाता बनाइदिनेछ। Joining is simple — click any 'Join Now' button and our team will register you within 5 minutes on WhatsApp.",
  },
  {
    question: "न्यूनतम जम्मा रकम कति हो? | What is the minimum deposit?",
    answer: "न्यूनतम जम्मा रकम मात्र NPR ५०० हो। हामी eSewa, Khalti, IME Pay, FonePay, ConnectIPS र बैंक ट्रान्सफर स्वीकार गर्छौं। The minimum deposit is just NPR 500 via eSewa, Khalti, IME Pay, bank transfer and more.",
  },
  {
    question: "निकासी कति छिटो हुन्छ? | How fast are withdrawals?",
    answer: "GorkhaBooks ले सबै निकासी ५ मिनेटभित्र प्रक्रिया गर्छ। NPR ५०,०००  सम्मका निकासी तत्काल हुन्छन्। All withdrawals under NPR 50,000 are processed within 5 minutes — guaranteed.",
  },
  {
    question: "GorkhaBooks सुरक्षित छ? | Is GorkhaBooks safe and secure?",
    answer: "हो, बिल्कुल। GorkhaBooks ले 256-bit SSL एन्क्रिप्सन र उन्नत सुरक्षा प्रोटोकलहरू प्रयोग गर्छ। तपाईंको पैसा र डेटा सधैं सुरक्षित छ। Yes — we use 256-bit SSL encryption. Your funds and data are 100% safe.",
  },
  {
    question: "कुन-कुन खेलमा बेट गर्न सकिन्छ? | What sports can I bet on?",
    answer: "Cricket, Football, Tennis, Kabaddi, Basketball, Esports (PUBG, Free Fire, Valorant) र अरू धेरैमा बेट गर्न सकिन्छ। लाइभ बेटिङ पनि उपलब्ध छ। We offer Cricket, Football, Kabaddi, Esports and more — including live in-play betting.",
  },
  {
    question: "पुराना खेलाडीहरूले पनि बोनस पाउँछन्? | Are there bonuses for existing players?",
    answer: "हो! हाम्रो साप्ताहिक Cashback, Reload Bonus, दैनिक Login Reward, Referral Bonus र VIP Program सधैं चालू छन्। Yes — weekly cashback, reload bonuses, daily login rewards, referral bonuses and VIP lifetime perks.",
  },
  {
    question: "मोबाइलमा खेल्न मिल्छ? | Can I play on mobile?",
    answer: "GorkhaBooks मोबाइलमा पूर्ण रूपमा अप्टिमाइज गरिएको छ। कुनै App डाउनलोड नगरी सिधै ब्राउजरमा खेल्न सकिन्छ। GorkhaBooks is fully mobile-optimised — play any game on any smartphone, no app download needed.",
  },
  {
    question: "Customer Support कसरी सम्पर्क गर्ने? | How do I contact support?",
    answer: "हाम्रो २४/७ सपोर्ट टोली WhatsApp मा उपलब्ध छ। वेबसाइटको WhatsApp बटन थिच्नुस् — ३० सेकेन्डभित्र जवाफ पाउनुहुनेछ। Our 24/7 team is on WhatsApp — click any button and get a reply within 30 seconds.",
  },
];

export const LIVE_MATCHES = [
  {
    id: 1,
    sport: "Cricket",
    tournament: "IPL 2026",
    team1: "Mumbai Indians",
    team2: "CSK",
    score1: "187/4",
    score2: "142/6",
    overs: "18.2 / 20",
    status: "LIVE",
    odds1: "1.45",
    oddsDraw: "8.00",
    odds2: "2.90",
    time: "🔴 LIVE",
  },
  {
    id: 2,
    sport: "Football",
    tournament: "Premier League",
    team1: "Arsenal",
    team2: "Chelsea",
    score1: "2",
    score2: "1",
    overs: "67'",
    status: "LIVE",
    odds1: "1.70",
    oddsDraw: "3.50",
    odds2: "4.20",
    time: "🔴 LIVE",
  },
  {
    id: 3,
    sport: "Tennis",
    tournament: "Wimbledon 2026",
    team1: "Djokovic",
    team2: "Alcaraz",
    score1: "6-4, 3",
    score2: "2, 2",
    overs: "Set 3",
    status: "LIVE",
    odds1: "2.10",
    oddsDraw: "-",
    odds2: "1.75",
    time: "🔴 LIVE",
  },
  {
    id: 4,
    sport: "Cricket",
    tournament: "Nepal T20 League",
    team1: "Pokhara Avengers",
    team2: "Kathmandu Kings",
    score1: "TBD",
    score2: "TBD",
    overs: "Upcoming",
    status: "UPCOMING",
    odds1: "1.85",
    oddsDraw: "9.00",
    odds2: "2.05",
    time: "⏰ आज साँझ ६:००",
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    title: "IPL 2025 Betting Guide: Top Teams to Back This Season",
    category: "Cricket",
    excerpt: "Complete analysis of IPL 2025 teams, player form, and best betting strategies to maximize your winnings this season.",
    date: "May 7, 2025",
    readTime: "5 min read",
    image: "/blog/ipl-guide.jpg",
    badge: "HOT",
    color: "red",
  },
  {
    id: 2,
    title: "Top 5 Teen Patti Strategies That Actually Work",
    category: "Casino",
    excerpt: "Master the art of Teen Patti with these proven strategies used by professional players to consistently win big.",
    date: "May 5, 2025",
    readTime: "7 min read",
    image: "/blog/teenpatti.jpg",
    badge: "FEATURED",
    color: "yellow",
  },
  {
    id: 3,
    title: "How to Claim Your Welcome Bonus: Step by Step Guide",
    category: "Bonuses",
    excerpt: "New to GorkhaBooks? Here's your complete guide to claiming your 100% welcome bonus and making the most of it.",
    date: "May 3, 2025",
    readTime: "3 min read",
    image: "/blog/bonus.jpg",
    badge: "GUIDE",
    color: "green",
  },
  {
    id: 4,
    title: "Nepal's Rising Esports Scene: Best Games to Bet On",
    category: "Esports",
    excerpt: "Nepal's esports industry is exploding. Find out which games and tournaments offer the best betting opportunities.",
    date: "May 1, 2025",
    readTime: "6 min read",
    image: "/blog/esports.jpg",
    badge: "NEW",
    color: "purple",
  },
  {
    id: 5,
    title: "Responsible Gambling: Playing Smart and Staying Safe",
    category: "Tips",
    excerpt: "Important guidelines to enjoy gaming responsibly and maintain a healthy balance while having fun.",
    date: "Apr 28, 2025",
    readTime: "4 min read",
    image: "/blog/responsible.jpg",
    badge: "IMPORTANT",
    color: "blue",
  },
  {
    id: 6,
    title: "Champions League Final Predictions & Betting Tips",
    category: "Football",
    excerpt: "Our expert analysts break down the UCL Final matchup with detailed predictions and value betting opportunities.",
    date: "Apr 25, 2025",
    readTime: "8 min read",
    image: "/blog/ucl.jpg",
    badge: "TRENDING",
    color: "orange",
  },
];

export const NOTIFICATION_MESSAGES = [
  { name: "Ram Shrestha",  location: "Kathmandu", action: "जित्यो / won",     amount: "NPR 32,000", game: "Cricket Betting" },
  { name: "Sita Tamang",   location: "Pokhara",   action: "जोडियो / joined",  amount: "",         game: "" },
  { name: "Binod KC",      location: "Lalitpur",  action: "जित्यो / won",     amount: "NPR 15,500", game: "Teen Patti" },
  { name: "Priya Rana",    location: "Biratnagar",action: "निकाल्यो / withdrew",amount:"NPR 48,000", game: "" },
  { name: "Suraj Ale",     location: "Chitwan",   action: "जित्यो / won",     amount: "NPR 8,200",  game: "Live Roulette" },
  { name: "Maya Gurung",   location: "Bhaktapur", action: "जोडियो / joined",  amount: "",         game: "" },
  { name: "Dipak Magar",   location: "Dharan",    action: "जित्यो / won",     amount: "NPR 25,000", game: "Football Betting" },
  { name: "Kabita Limbu",  location: "Hetauda",   action: "निकाल्यो / withdrew",amount:"NPR 72,000", game: "" },
];
