import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import FloatingWhatsApp from "@/components/FloatingWhatsApp";
import AutoRedirect from "@/components/AutoRedirect";
import ScrollProgress from "@/components/ScrollProgress";
import NotificationPopup from "@/components/NotificationPopup";
import MobileBottomCTA from "@/components/MobileBottomCTA";
import TrustBar from "@/components/TrustBar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "Online Betting Nepal | Best eSewa & Khalti Casino 2026 | GorkhaBooks",
    template: "%s | GorkhaBooks Nepal – gorkha.com",
  },
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
    apple: "/logo.png",
  },
  description:
    "GorkhaBooks – नेपालको #१ अनलाइन बेटिङ र क्यासिनो। eSewa, Khalti, IME Pay। IPL क्रिकेट, फुटबल, Teen Patti, Aviator। ५ मिनेटमा निकासी। Nepal's most trusted online betting site – fast withdrawal, real money casino, sports betting & live casino.",
  keywords: [
    // Brand core
    "GorkhaBooks", "gorkha.com", "GorkhaBooks Nepal", "Gorkha gaming Nepal",
    "Nepal gaming site 2026", "Gorkha bet", "GorkhaBooks betting site",
    "गोर्खाबुक्स", "गोर्खा गेमिङ", "नेपाल गेमिङ",
    // Online gaming Nepal
    "online gaming Nepal 2026", "best gaming site Nepal", "Nepal gaming platform",
    "top gaming website Nepal", "real money gaming Nepal", "mobile gaming Nepal",
    "gaming app Nepal", "multiplayer online games Nepal", "PC gaming Nepal",
    // Sports betting
    "online betting Nepal", "sports betting Nepal 2026", "cricket betting Nepal",
    "IPL 2026 betting Nepal", "football betting Nepal", "live betting Nepal",
    "kabaddi betting Nepal", "tennis betting Nepal", "Nepal Premier League bet",
    "best odds cricket Nepal", "live sports betting Nepal", "satta Nepal",
    // Esports
    "esports Nepal 2026", "PUBG tournament Nepal", "Free Fire tournament Nepal",
    "BGMI tournament Nepal", "Valorant Nepal", "esports betting Nepal",
    "online esports platform Nepal", "esports team Nepal", "gaming tournament Nepal",
    "competitive gaming Nepal", "ranked gaming Nepal", "Nepal esports community",
    "how to join esports Nepal", "best esports site Nepal 2026",
    // Casino
    "live casino Nepal", "Teen Patti online Nepal", "Andar Bahar Nepal",
    "online roulette Nepal", "online blackjack Nepal", "slot games Nepal",
    "live dealer Nepal", "casino games Nepal 2026", "jackpot Nepal",
    // Community & local
    "Kathmandu online gaming", "Pokhara betting site", "Nepal gamers community",
    "Nepali gamers network", "Nepal gaming news 2026", "gaming events Nepal",
    "fastest growing gaming community Nepal", "Nepali gaming YouTube",
    // Payments
    "eSewa betting Nepal", "Khalti casino Nepal", "IME Pay gaming Nepal",
    "FonePay bet Nepal", "NPR betting site", "instant withdrawal Nepal",
    // Trust & intent
    "trusted betting site Nepal", "safe betting Nepal", "legal gaming Nepal",
    "licensed betting Nepal", "secure online casino Nepal", "fair gaming Nepal",
    "WhatsApp betting Nepal", "100% welcome bonus Nepal",
    // Cricket Betting Nepal
    "cricket betting nepal", "IPL betting nepal", "T20 betting nepal", "ODI betting nepal", "test match betting nepal",
    "live cricket bet nepal", "cricket match prediction nepal", "cricket satta nepal", "IPL satta nepal",
    "world cup betting nepal", "cricket toss bet nepal", "cricket score bet nepal", "best cricket betting site nepal",
    "cricket betting odds nepal", "cricket bet win nepal", "ipl winner bet nepal", "cricket fantasy bet nepal",
    "cricket jackpot nepal", "big bash betting nepal", "asia cup betting nepal", "Champions Trophy bet nepal",
    "cricket bet app nepal", "cricket bet tips nepal", "cricket live bet nepal", "cricket back lay nepal",
    "cricket exchange bet nepal", "cricket win real money nepal", "nepal cricket bet", "online cricket bet nepal",
    "cricket betting bonus nepal",
    // Football Betting Nepal
    "football betting nepal", "EPL betting nepal", "La Liga betting nepal", "UCL betting nepal", "FIFA betting nepal",
    "Champions League bet nepal", "football match bet nepal", "football live bet nepal", "football odds nepal",
    "football prediction nepal", "football satta nepal", "football win nepal", "best football betting nepal",
    "Nepal football bet", "football jackpot nepal", "football double chance nepal", "football over under bet nepal",
    "football BTTS nepal", "football accumulator nepal", "football parlay nepal", "football 1x2 bet nepal",
    "football handicap bet nepal", "football correct score nepal", "football goalscorer bet nepal",
    "football bet app nepal", "Serie A bet nepal", "Bundesliga bet nepal", "Ligue 1 bet nepal", "MLS bet nepal",
    "football bet real money nepal",
    // Live Betting Nepal
    "live betting nepal", "in-play bet nepal", "live sports bet nepal", "real time bet nepal", "live odds nepal",
    "live cricket bet nepal", "live football bet nepal", "live casino nepal", "live dealer bet nepal",
    "live baccarat nepal", "live roulette nepal", "live blackjack nepal", "live teen patti nepal",
    "live andar bahar nepal", "live dragon tiger nepal", "live game show nepal", "live bet win nepal",
    "live score bet nepal", "live wager nepal", "in-play odds nepal", "live accumulator nepal",
    "cash out bet nepal", "bet cash out nepal", "live streaming bet nepal", "watch and bet nepal",
    "live market nepal betting", "instant bet nepal", "live bonus bet nepal", "live jackpot nepal", "live bet app nepal",
    // Other Sports Nepal
    "kabaddi betting nepal", "kabaddi bet nepal", "Pro Kabaddi bet nepal", "kabaddi match prediction nepal",
    "kabaddi satta nepal", "kabaddi online bet nepal", "kabaddi win nepal", "kabaddi jackpot nepal",
    "volleyball betting nepal", "basketball betting nepal", "Nepal Premier League bet", "Nepal football league bet",
    "table tennis betting nepal", "badminton betting nepal", "boxing betting nepal", "MMA betting nepal",
    "UFC betting nepal", "wrestling bet nepal", "athletics bet nepal", "marathon bet nepal",
    "cycling bet nepal", "chess bet nepal", "darts betting nepal", "snooker betting nepal",
    "hockey betting nepal", "archery bet nepal", "Nepal sports prediction", "local sports bet nepal",
    "Nepal league bet", "Nepal national team bet",
    // Casino Games Nepal
    "teen patti nepal", "teen patti real money nepal", "teen patti online nepal", "andar bahar nepal",
    "andar bahar real cash nepal", "andar bahar online nepal", "dragon tiger nepal", "dragon tiger real money nepal",
    "baccarat nepal", "baccarat real money nepal", "live baccarat nepal", "blackjack nepal",
    "blackjack real money nepal", "poker nepal", "Texas Holdem nepal", "Omaha poker nepal", "rummy nepal",
    "online rummy nepal", "rummy real money nepal", "3 patti nepal", "3 patti gold nepal",
    "card game real money nepal", "casino card game nepal", "online card game nepal", "table game nepal",
    "casino table nepal", "casino real cash nepal", "card bet nepal", "play cards online nepal", "win cards nepal",
    // Crash & Instant Games Nepal
    "crash game nepal", "aviator game nepal", "aviator bet nepal", "aviator win nepal", "aviator real money nepal",
    "JetX nepal", "spaceman game nepal", "crash bet nepal", "crash multiplier nepal", "mines game nepal",
    "plinko nepal", "dice game nepal", "hilo game nepal", "fast game nepal", "instant game nepal",
    // Slots Nepal
    "slot game nepal", "slots real money nepal", "jackpot slots nepal", "mega jackpot nepal",
    "progressive jackpot nepal", "free spins slots nepal", "bonus buy slots nepal", "3 reel slot nepal",
    "5 reel slot nepal", "video slot nepal", "fruit slot nepal", "classic slots nepal", "megaways nepal",
    "cluster slot nepal", "big win slots nepal",
    // Betting Tips Nepal
    "betting tips nepal", "free bet tips nepal", "today match prediction nepal", "cricket prediction nepal",
    "football prediction nepal", "sure bet nepal", "sure win bet nepal", "fixed match nepal",
    "betting strategy nepal", "how to win bet nepal", "bet guide nepal", "betting odds explained nepal",
    "matched betting nepal", "value bet nepal", "accumulator tips nepal", "parlay tips nepal",
    "daily prediction nepal", "win every bet nepal", "betting analysis nepal", "expert prediction nepal",
    "best odds nepal", "betting system nepal", "handicap tip nepal", "over under tip nepal",
    "football tips today nepal", "cricket tips today nepal", "free prediction site nepal", "prediction app nepal",
    "sports analysis nepal", "betting forecast nepal",
    // Betting Bonus Nepal
    "betting bonus nepal", "free bet nepal", "no deposit free bet nepal", "welcome bet bonus nepal",
    "first bet bonus nepal", "matched bet bonus nepal", "reload bet bonus nepal", "accumulator bonus nepal",
    "acca insurance nepal", "bet refund nepal", "money back bet nepal", "cashback bet nepal",
    "bet boost nepal", "odds boost nepal", "enhanced odds nepal", "bet promo code nepal",
    "betting voucher nepal", "bet coupon nepal", "loyalty bet bonus nepal", "vip bet nepal",
    "high roller bonus nepal", "weekly bet bonus nepal", "daily free bet nepal", "bet and get nepal",
    "refer earn bet nepal", "bet affiliate nepal", "bet reward nepal", "winning reward nepal",
    "bonus rollover nepal", "wagering requirement nepal",
    // Betting Apps Nepal
    "betting app nepal", "best betting app nepal", "bet app download nepal", "mobile bet nepal",
    "bet on mobile nepal", "android bet app nepal", "ios betting app nepal", "betting website nepal",
    "best bet site nepal", "top betting site nepal", "new betting site nepal", "trusted bet site nepal",
    "licensed bet site nepal", "bet365 nepal alternative", "1xbet nepal alternative", "betway nepal alternative",
    "betwinner nepal", "melbet nepal", "mostbet nepal", "parimatch nepal", "22bet nepal",
    "bet platform nepal", "nepali betting platform", "local bet app nepal", "nepal betting platform 2025",
    "online bet nepal", "bet nepal app", "bet nepal site", "sportsbook app nepal", "fast bet app nepal",
    // Nepali Keywords
    "सट्टाबाजी नेपाल", "अनलाइन सट्टा नेपाल", "क्रिकेट सट्टा नेपाल", "फुटबल सट्टा नेपाल",
    "कबड्डी सट्टा नेपाल", "लाइभ बेट नेपाल", "बेटिङ नेपाल", "अनलाइन बेट नेपाल", "खेल बेटिङ नेपाल",
    "नेपाल बेटिङ एप", "satta nepal", "satta online nepal", "cricket satta nepal", "football satta nepal",
    "IPL satta nepal", "satta matka nepal", "kabaddi satta nepal", "satta result nepal", "satta win nepal",
    "satta app nepal",
    // Local Nepal Cities
    "bet nepal kathmandu", "bet nepal pokhara", "bet nepal chitwan", "bet nepal biratnagar",
    "bet nepal butwal", "bet nepal lalitpur", "bet nepal bhaktapur", "bet nepal hetauda",
    "online satta real money nepal", "satta bonus nepal",
    // GorkhaBooks Brand Keywords
    "gorkhabooks", "gorkha books", "gorkhabooks nepal", "gorkhabooks gaming", "gorkhabooks site",
    "gorkhabooks online", "gorkha books nepal gaming", "gorkhabooks login", "gorkhabooks register",
    "gorkhabooks app", "gorkhabooks review", "gorkhabooks promo", "gorkhabooks bonus",
    "gorkhabooks deposit", "gorkhabooks withdrawal", "gorkhabooks payment", "gorkhabooks support",
    "gorkhabooks customer care", "gorkhabooks contact", "gorkhabooks referral", "gorkhabooks affiliate",
    "gorkhabooks free", "gorkhabooks winner", "gorkhabooks jackpot", "gorkhabooks account",
    "gorkhabooks new account", "gorkhabooks verify", "gorkhabooks official", "gorkhabooks trusted",
    "gorkhabooks legit",
    // Online Gaming Nepal
    "online gaming nepal", "gaming site nepal", "nepal gaming platform", "best gaming site nepal",
    "online games nepal", "play games online nepal", "gaming nepal 2025", "nepal game app",
    "top gaming sites nepal", "gaming website nepal", "free gaming nepal", "nepal real money games",
    "gaming in nepal", "play and win nepal", "win real money nepal", "nepal online game",
    "earn money gaming nepal", "game nepal", "mobile gaming nepal", "internet gaming nepal",
    "nepal gaming industry", "online entertainment nepal", "digital games nepal", "best online games nepal",
    "real money gaming nepal", "nepal gaming 2024", "nepal gaming apps", "gaming bonus nepal",
    "play win earn nepal", "online game nepal",
    // Sports Betting Nepal
    "sports betting nepal", "bet online nepal", "nepal sports bet", "football betting nepal",
    "cricket betting nepal", "IPL betting nepal", "kabaddi betting nepal", "live betting nepal",
    "sports book nepal", "sportsbook nepal", "bet nepal", "online bet nepal", "best sportsbook nepal",
    "betting odds nepal", "nepal betting app", "bet on sports nepal", "legal sports betting nepal",
    "sports wager nepal", "cricket bet nepal", "football bet nepal", "basketball betting nepal",
    "tennis betting nepal", "esports betting nepal", "virtual sports nepal", "bet365 nepal",
    "1xbet nepal", "betway nepal", "bewin nepal", "sportsbetting app nepal", "nepal sports wagering",
    // Online Casino Nepal
    "online casino nepal", "casino nepal", "slot games nepal", "slots nepal", "nepal casino",
    "live casino nepal", "casino online nepal", "best casino nepal", "casino bonus nepal",
    "real money casino nepal", "casino games nepal", "slot machine nepal", "jackpot nepal",
    "roulette nepal", "blackjack nepal", "baccarat nepal", "teen patti nepal", "andar bahar nepal",
    "poker nepal", "online poker nepal", "teen patti online nepal", "casino app nepal",
    "live dealer nepal", "casino deposit nepal", "casino withdrawal nepal", "free spins nepal",
    "casino welcome bonus nepal", "slot bonus nepal", "spin and win nepal", "demo slots nepal",
    // Lottery Nepal
    "lottery nepal", "online lottery nepal", "nepal lottery", "lucky draw nepal", "prediction game nepal",
    "number game nepal", "lucky number nepal", "win lottery nepal", "lottery result nepal",
    "lotto nepal", "online lotto nepal", "lottery ticket nepal", "lucky win nepal", "daily lottery nepal",
    "nepal jackpot lottery", "color prediction nepal", "color game nepal", "1 minute game nepal",
    "fast game nepal", "prediction site nepal", "wingo nepal", "big small game nepal",
    "number prediction nepal", "win prize nepal", "lottery app nepal", "lottery draw nepal",
    "online draw nepal", "daily win nepal", "instant lottery nepal", "lucky numbers nepal",
    // Esports Nepal
    "esports nepal", "nepal esports", "pubg nepal", "free fire nepal", "valorant nepal",
    "call of duty nepal", "minecraft nepal", "mobile legends nepal", "bgmi nepal",
    "gaming tournament nepal", "esports tournament nepal", "online tournament nepal",
    "pubg tournament nepal", "free fire tournament nepal", "valorant tournament nepal",
    "esports betting nepal", "esports prize nepal", "esports team nepal", "game streaming nepal",
    "gaming community nepal", "nepali gamers", "nepal game tournament", "competitive gaming nepal",
    "esports league nepal", "gaming clan nepal", "game championship nepal", "online gaming competition nepal",
    "nepal gaming championship", "mobile gaming tournament nepal", "gaming news nepal",
    // Payment Nepal Gaming
    "esewa nepal gaming", "khalti nepal gaming", "imeepay gaming", "connect ips gaming nepal",
    "bank transfer gaming nepal", "upi nepal gaming", "instant withdrawal nepal", "fast payout nepal",
    "nepal payment gateway gaming", "secure payment nepal gaming", "deposit by esewa",
    "deposit by khalti", "online payment gaming nepal", "nepal digital payment gaming",
    "minimum deposit nepal gaming", "no deposit bonus nepal", "free bonus nepal", "cashback nepal gaming",
    "nepal gaming wallet", "safe deposit nepal", "crypto gaming nepal", "btc gaming nepal",
    "usdt gaming nepal", "e-wallet nepal gaming", "quick payout nepal", "nepal gaming rewards",
    "real cash nepal games", "money gaming nepal", "pay and play nepal", "gaming payment nepal",
    // Nepali Keywords
    "नेपाल गेमिङ", "नेपाल अनलाइन गेम", "गोर्खाबुक्स", "नेपाल सट्टाबाजी",
    "नेपाली क्यासिनो", "नेपाल लटरी", "अनलाइन खेल नेपाल", "नेपाल जित्ने खेल",
    "नेपाल गेम एप", "मोबाइल गेमिङ नेपाल",
    // Local Gaming Nepal
    "nepali gaming site", "nepali game", "khel nepal", "online khel nepal", "nepali casino",
    "nepali lottery", "nepali sports bet", "nepali gamers", "gaming kathmandu", "gaming pokhara",
    "gaming lalitpur", "gaming bhaktapur", "gaming chitwan", "gaming butwal", "gaming biratnagar",
    "gaming dharan", "gaming hetauda", "gaming nepalgunj", "gaming birgunj",
    // Legal Gaming Nepal
    "legal gaming nepal", "licensed gaming nepal", "safe gaming nepal", "trusted gaming nepal",
    "secure casino nepal", "verified gaming nepal", "fair play gaming nepal", "responsible gaming nepal",
    "certified gaming nepal", "regulated gaming nepal", "is online gaming legal nepal", "gaming laws nepal",
    "nepal gambling law", "gaming license nepal", "RNG certified nepal", "provably fair nepal",
    "ssl secured gaming nepal", "data privacy gaming nepal", "safe bet nepal", "anti fraud gaming nepal",
    "real money safe nepal", "scam free gaming nepal", "honest gaming nepal", "transparent gaming nepal",
    "24/7 support nepal gaming", "gaming help nepal", "nepal gaming complaint", "dispute resolution gaming nepal",
    "player protection nepal", "age verification gaming nepal",
    // Gaming Bonus Nepal
    "gaming bonus nepal", "welcome bonus nepal", "signup bonus nepal", "first deposit bonus nepal",
    "free bonus nepal gaming", "no deposit bonus nepal gaming", "reload bonus nepal", "cashback gaming nepal",
    "loyalty program nepal gaming", "vip gaming nepal", "refer and earn nepal gaming", "free spins nepal gaming",
    "promo code nepal gaming", "daily bonus nepal gaming", "weekly bonus nepal gaming", "jackpot bonus nepal",
    "tournament prize nepal", "prize pool nepal gaming", "winning prize nepal", "earn online nepal",
    "passive income gaming nepal", "earn from home nepal gaming", "best bonus site nepal", "biggest jackpot nepal",
    "mega win nepal", "lucky bonus nepal", "instant bonus nepal", "exclusive bonus nepal", "seasonal promo nepal gaming",
    "nepal gaming festival offer",
    "instant payout Nepal", "best withdrawal speed Nepal",
    // 2026 STRATEGY — High competition core
    "best betting site Nepal", "real money games Nepal", "betting app Nepal",
    "online gambling Nepal", "Nepal betting platform", "online wagering Nepal",
    // 2026 STRATEGY — High conversion money keywords
    "Khalti betting Nepal", "fast withdrawal casino Nepal",
    "instant payout betting Nepal", "IME Pay betting Nepal",
    "deposit bonus Nepal betting", "minimum deposit betting Nepal",
    "withdraw winnings Nepal", "mobile wallet betting Nepal",
    "same day withdrawal Nepal", "bank transfer betting Nepal",
    "betting deposit methods Nepal", "Nepal rupees betting",
    "no minimum deposit casino Nepal",
    // 2026 STRATEGY — Medium competition long-tail
    "how to bet online in Nepal", "best time to bet on IPL Nepal",
    "Nepal cricket betting guide", "online casino with eSewa Nepal",
    "betting sites that accept Khalti", "fast withdrawal betting Nepal",
    "how to deposit on betting sites Nepal", "safest betting app Nepal 2026",
    "beginner guide to online betting Nepal", "Nepal football betting tips",
    "mobile betting Nepal guide", "best betting strategy Nepal",
    "online casino minimum deposit Nepal", "Nepal sports betting for beginners",
    "live casino Nepal review", "how to verify betting account Nepal",
    "Nepal betting sites comparison", "which betting site pays fast Nepal",
    "online betting age limit Nepal", "Nepal casino games explained",
    // 2026 STRATEGY — Competitor target keywords
    "best betting site Nepal vs MelBet", "MelBet Nepal alternative",
    "1xBet Nepal vs GorkhaBooks", "better than 1xBet Nepal",
    "Parimatch Nepal alternative", "safest betting platform Nepal comparison",
    "trusted site vs MelBet Nepal", "Nepal betting site reviews 2026",
    "top 10 betting sites Nepal 2026", "fastest payout vs competitors Nepal",
    // 2026 STRATEGY — Casino games
    "aviator game Nepal", "mines game Nepal", "Dragon Tiger Nepal",
    "Rummy online Nepal", "how to play Teen Patti online Nepal",
    "Aviator game Nepal strategy", "how to win aviator Nepal",
    // 2026 STRATEGY — City targeting
    "online betting Kathmandu", "online betting Pokhara",
    "online betting Biratnagar", "online betting Nepalganj",
    // Additional Nepal betting keywords
    "Nepal betting", "Nepal gambling", "Nepal sportsbook", "Nepal odds",
    "Nepal casino", "Nepal cricket bet", "Nepal football bet", "Nepal wager",
    "Nepal lottery", "Nepal bookmaker", "Nepal betting sites", "Nepal betting apps",
    "Nepal online betting", "Nepal betting platform", "Nepal betting tips",
    "Nepal betting guide", "Nepal betting options", "Nepal betting market",
    "Nepal betting login", "Nepal betting signup",
    "best betting sites in Nepal", "best online betting sites Nepal",
    "top betting sites Nepal", "trusted betting sites in Nepal",
    "licensed betting sites Nepal", "safe betting sites Nepal",
    "legal betting platforms Nepal", "new betting sites Nepal",
    "betting sites that accept Nepal users", "betting sites with NPR currency",
    "betting apps Nepal Android", "betting apps Nepal iOS",
    "Nepal betting site registration", "Nepal betting site bonus",
    "betting site welcome offer Nepal", "online betting in Nepal",
    "online sports betting Nepal", "online betting Nepal legal",
    "online betting Nepal for beginners", "online gambling Nepal real money",
    "online betting Nepal mobile", "internet betting Nepal",
    "real money betting Nepal", "online betting Nepal payment methods",
    "deposit methods Nepal betting", "Nepal betting with eSewa",
    "Nepal betting with Khalti", "Nepal betting bank transfer",
    "Nepal cricket betting", "cricket betting in Nepal",
    "Nepal cricket match betting", "T20 cricket betting Nepal",
    "Nepal national cricket team bet", "Nepal football betting sites",
    "soccer betting Nepal", "kabaddi betting Nepal",
    "volleyball betting Nepal", "basketball betting Nepal",
    "tennis betting Nepal", "horse racing betting Nepal",
    "virtual sports betting Nepal",
    // Additional beginner guide/how-to keywords
    "xbetting guide for beginners Nepal", "how to bet in Nepal step by step",
    "Nepal betting tutorial", "understanding betting odds Nepal",
    "how to read betting odds in Nepal", "types of bets in Nepal",
    "sports betting basics Nepal", "beginner sports betting Nepal",
    "Nepal betting explained", "what is a sportsbook Nepal",
    "Nepal betting terminology",
    // Betting tips/predictions
    "Nepal betting tips today", "Nepal betting predictions",
    "Nepal cricket betting tips", "Nepal football betting tips",
    "betting strategy Nepal", "best betting strategy for Nepalese bettors",
    "how to win at sports betting Nepal", "value betting Nepal",
    "handicap betting Nepal", "over/under betting Nepal",
    "accumulator betting Nepal", "live betting tips Nepal",
    // Comparison/review keywords
    "Nepal betting site comparison", "compare betting sites Nepal",
    "Nepal betting site review 2025", "best odds betting site Nepal",
    "highest bonus betting site Nepal", "betting site with best welcome bonus Nepal",
    "1xBet Nepal review", "Bet365 Nepal review", "Parimatch Nepal review",
    "Melbet Nepal review", "22Bet Nepal review", "Betway Nepal review",
    "which sportsbook is best for Nepal", "pros and cons of betting sites Nepal",
    // Live betting keywords
    "live betting Nepal", "in-play betting Nepal", "live odds Nepal",
    "real-time betting Nepal", "live cricket odds Nepal",
    "live football odds Nepal", "cash out betting Nepal",
    // Bonus keywords
    "Nepal betting bonus", "betting welcome bonus Nepal",
    "free bets Nepal", "no deposit bonus Nepal betting",
    "Nepal betting promo code", "reload bonus Nepal betting",
    "VIP betting rewards Nepal", "cashback betting Nepal",
    // Location/regulatory keywords
    "betting in Pokhara Nepal", "betting sites Nepal Rupee",
    "sports gambling Nepal law", "Nepal gambling regulations",
    "Nepal Rastriya Banijya Bank betting",
    // Responsible gambling/cryptocurrency keywords
    "responsible gambling Nepal", "problem gambling help Nepal",
    "cryptocurrency betting Nepal", "Bitcoin betting Nepal",
    "USDT betting Nepal", "VPN betting Nepal",
    "betting with VPN in Nepal", "anonymous betting Nepal",
    "PayPal betting Nepal alternatives",
    // Additional 120+ Nepal betting keywords
    "nepal betting odds", "nepal betting lines", "nepal betting spreads",
    "nepal betting parlay", "nepal betting teaser", "nepal betting prop",
    "nepal betting futures", "nepal betting exchange", "nepal betting broker",
    "nepal betting agent", "nepal betting syndicate", "nepal betting tips telegram",
    "nepal betting whatsapp group", "nepal betting telegram channel",
    "nepal betting prediction site", "nepal betting analysis", "nepal betting statistics",
    "nepal betting data", "nepal betting trends", "nepal betting patterns",
    "nepal betting news", "nepal betting updates", "nepal betting results",
    "nepal betting scores", "nepal betting fixtures", "nepal betting schedule",
    "nepal betting calendar", "nepal betting events", "nepal betting tournaments",
    "nepal betting leagues", "nepal betting cups", "nepal betting championships",
    "nepal betting world cup", "nepal betting t20 world cup", "nepal betting ipl auction",
    "nepal betting cpl", "nepal betting bpl", "nepal betting psl", "nepal betting big bash",
    "nepal betting sa20", "nepal betting hundred", "nepal betting asia cup",
    "nepal betting champions trophy", "nepal betting test championship", "nepal betting odi ranking",
    "nepal betting t20 ranking", "nepal betting icc ranking", "nepal betting player stats",
    "nepal betting team stats", "nepal betting head to head", "nepal betting h2h",
    "nepal betting form guide", "nepal betting injury news", "nepal betting team news",
    "nepal betting weather report", "nepal betting pitch report", "nepal betting venue info",
    "nepal betting stadium info", "nepal betting ground info", "nepal betting toss prediction",
    "nepal betting playing xi", "nepal betting dream11", "nepal betting fantasy cricket",
    "nepal betting fantasy football", "nepal betting virtual betting", "nepal betting simulated betting",
    "nepal betting esports betting", "nepal betting mobile legends", "nepal betting free fire",
    "nepal betting pubg mobile", "nepal betting valorant", "nepal betting dota 2",
    "nepal betting cs go", "nepal betting lol", "nepal betting fifa", "nepal betting nba",
    "nepal betting nfl", "nepal betting mlb", "nepal betting nhl", "nepal betting ufc",
    "nepal betting boxing", "nepal betting mma", "nepal betting wrestling", "nepal betting f1",
    "nepal betting motogp", "nepal betting tennis atp", "nepal betting tennis wta",
    "nepal betting golf", "nepal betting snooker", "nepal betting darts", "nepal betting rugby",
    "nepal betting cricket world cup", "nepal betting football world cup", "nepal betting euro",
    "nepal betting copa america", "nepal betting afcon", "nepal betting asian games",
    "nepal betting olympics", "nepal betting commonwealth games", "nepal betting saff games",
    "nepal betting south asian games", "nepal betting domestic cricket", "nepal betting nepal premier league",
    "nepal betting everest premier league", "nepal betting dhangadhi premier league",
    "nepal betting pokhara premier league", "nepal betting departmental cricket",
    "nepal betting club cricket", "nepal betting inter school cricket", "nepal betting inter college cricket",
    "nepal betting university cricket", "nepal betting women cricket", "nepal betting u19 cricket",
    "nepal betting u16 cricket", "nepal betting domestic football", "nepal betting martyrs memorial a division",
    "nepal betting b division league", "nepal betting c division league", "nepal betting super league",
    "nepal betting women league", "nepal betting futsal", "nepal betting beach football",
    "nepal betting street football", "nepal betting volleyball league", "nepal basketball league",
    "nepal tennis open", "nepal golf open", "nepal marathon", "nepal cycling race",
    "nepal boxing championship", "nepal wrestling championship", "nepal martial arts",
    "nepal taekwondo", "nepal karate", "nepal judo", "nepal wushu",
    "nepal betting kabaddi league", "nepal pro kabaddi", "nepal betting hockey league",
    "nepal betting badminton open", "nepal betting table tennis", "nepal betting squash",
    "nepal betting esports league", "nepal gaming league", "nepal esports championship",
    "nepal gaming tournament", "nepal esports cup", "nepal gaming cup",
    "nepal betting live streaming", "nepal betting live score", "nepal betting live updates",
    "nepal betting live commentary", "nepal betting live odds", "nepal betting live markets",
    "nepal betting in play", "nepal betting cash out", "nepal betting edit bet",
    "nepal betting bet builder", "nepal betting same game multi", "nepal betting bet slip",
    "nepal betting receipt", "nepal betting history", "nepal betting my bets",
    "nepal betting open bets", "nepal betting settled bets", "nepal betting voided bets",
    "nepal betting won bets", "nepal betting lost bets", "nepal betting pending bets",
    "nepal betting account", "nepal betting profile", "nepal betting settings",
    "nepal betting preferences", "nepal betting notifications", "nepal betting alerts",
    "nepal betting promotions", "nepal betting offers", "nepal betting deals",
    "nepal betting vouchers", "nepal betting coupons", "nepal betting rewards",
    "nepal betting loyalty", "nepal betting vip", "nepal betting elite",
    "nepal betting platinum", "nepal betting gold", "nepal betting silver",
    "nepal betting bronze", "nepal betting tiers", "nepal betting levels",
    "nepal betting points", "nepal betting comp points", "nepal betting redeem",
    "nepal betting exchange", "nepal betting trade", "nepal betting lay",
    "nepal betting back", "nepal betting matched", "nepal betting unmatched",
    "nepal betting partial match", "nepal betting full match", "nepal betting odds movement",
    "nepal betting price change", "nepal betting drift", "nepal betting steam",
    "nepal betting line movement", "nepal betting market movement", "nepal betting volume",
    "nepal betting liquidity", "nepal betting depth", "nepal betting spread",
    "nepal betting commission", "nepal betting fee", "nepal betting charge",
    "nepal betting tax", "nepal betting levy", "nepal betting deduction",
    "nepal betting withholding", "nepal betting net", "nepal betting gross",
    "nepal betting payout", "nepal betting return", "nepal betting profit",
    "nepal betting loss", "nepal betting balance", "nepal betting bankroll",
    "nepal betting budget", "nepal betting limit", "nepal betting restriction",
    "nepal betting exclusion", "nepal betting timeout", "nepal betting self exclusion",
    "nepal betting cool off", "nepal betting break", "nepal betting pause",
    "nepal betting stop", "nepal betting quit", "nepal betting responsible",
    "nepal betting safer", "nepal betting protection", "nepal betting support",
    "nepal betting help", "nepal betting advice", "nepal betting guidance",
    "nepal betting education", "nepal betting awareness", "nepal betting prevention",
    "nepal betting recovery", "nepal betting rehabilitation", "nepal betting treatment",
    "nepal betting counseling", "nepal betting therapy", "nepal betting hotline",
    "nepal betting helpline", "nepal betting emergency", "nepal betting crisis",
    "nepal betting intervention", "nepal betting assistance", "nepal betting resources",
    "nepal betting tools", "nepal betting calculators", "nepal betting converters",
    "nepal betting odds calculator", "nepal betting parlay calculator", "nepal betting payout calculator",
    "nepal betting margin calculator", "nepal betting arbitrage calculator", "nepal betting value calculator",
    "nepal betting kelly calculator", "nepal betting staking calculator", "nepal betting bankroll calculator",
    "nepal betting roi calculator", "nepal betting yield calculator", "nepal betting profit calculator",
    "nepal betting loss calculator", "nepal betting break even calculator", "nepal betting variance calculator",
    "nepal betting standard deviation", "nepal betting sharpe ratio", "nepal betting maximum drawdown",
    "nepal betting win rate", "nepal betting hit rate", "nepal betting strike rate",
    "nepal betting success rate", "nepal betting accuracy", "nepal betting precision",
    "nepal betting consistency", "nepal betting stability", "nepal betting reliability",
    "nepal betting trust", "nepal betting confidence", "nepal betting reputation",
    "nepal betting credibility", "nepal betting authenticity", "nepal betting legitimacy",
    "nepal betting validity", "nepal betting verification", "nepal betting certification",
    "nepal betting accreditation", "nepal betting endorsement", "nepal betting approval",
    "nepal betting authorization", "nepal betting license", "nepal betting permit",
    "nepal betting registration", "nepal betting enrollment", "nepal betting subscription",
    "nepal betting membership", "nepal betting affiliation", "nepal betting partnership",
    "nepal betting collaboration", "nepal betting alliance", "nepal betting association",
    "nepal betting federation", "nepal betting union", "nepal betting organization",
    "nepal betting institution", "nepal betting establishment", "nepal betting company",
    "nepal betting corporation", "nepal betting enterprise", "nepal betting business",
    "nepal betting venture", "nepal betting startup", "nepal betting initiative",
    "nepal betting project", "nepal betting program", "nepal betting scheme",
    "nepal betting plan", "nepal betting strategy", "nepal betting tactic",
    "nepal betting method", "nepal betting approach", "nepal betting technique",
    "nepal betting system", "nepal betting framework", "nepal betting structure",
    "nepal betting model", "nepal betting pattern", "nepal betting algorithm",
    "nepal betting formula", "nepal betting equation", "nepal betting calculation",
    "nepal betting computation", "nepal betting analysis", "nepal betting evaluation",
    "nepal betting assessment", "nepal betting review", "nepal betting audit",
    "nepal betting inspection", "nepal betting examination", "nepal betting investigation",
    "nepal betting inquiry", "nepal betting study", "nepal betting research",
    "nepal betting survey", "nepal betting poll", "nepal betting questionnaire",
    "nepal betting interview", "nepal betting discussion", "nepal betting debate",
    "nepal betting dialogue", "nepal betting conversation", "nepal betting communication",
    "nepal betting interaction", "nepal betting engagement", "nepal betting participation",
    "nepal betting involvement", "nepal betting contribution", "nepal betting input",
    "nepal betting feedback", "nepal betting suggestion", "nepal betting recommendation",
    "nepal betting proposal", "nepal betting submission", "nepal betting application",
    "nepal betting request", "nepal betting demand", "nepal betting requirement",
    "nepal betting specification", "nepal betting criteria", "nepal betting standard",
    "nepal betting guideline", "nepal betting protocol", "nepal betting procedure",
    "nepal betting process", "nepal betting workflow", "nepal betting pipeline",
    "nepal betting cycle", "nepal betting sequence", "nepal betting order",
    "nepal betting arrangement", "nepal betting organization", "nepal betting coordination",
    "nepal betting management", "nepal betting administration", "nepal betting supervision",
    "nepal betting control", "nepal betting regulation", "nepal betting governance",
    "nepal betting oversight", "nepal betting monitoring", "nepal betting tracking",
    "nepal betting reporting", "nepal betting documentation", "nepal betting recording",
    "nepal betting logging", "nepal betting archiving", "nepal betting storage",
    "nepal betting backup", "nepal betting recovery", "nepal betting restoration",
    "nepal betting retrieval", "nepal betting access", "nepal betting availability",
    "nepal betting accessibility", "nepal betting usability", "nepal betting user experience",
    "nepal betting ux", "nepal betting ui", "nepal betting interface",
    "nepal betting design", "nepal betting layout", "nepal betting structure",
    "nepal betting architecture", "nepal betting infrastructure", "nepal betting foundation",
    "nepal betting platform", "nepal betting system", "nepal betting solution",
    "nepal betting service", "nepal betting product", "nepal betting offering",
    "nepal betting feature", "nepal betting functionality", "nepal betting capability",
    "nepal betting capacity", "nepal betting ability", "nepal betting skill",
    "nepal betting expertise", "nepal betting knowledge", "nepal betting understanding",
    "nepal betting insight", "nepal betting wisdom", "nepal betting intelligence",
    "nepal betting information", "nepal betting data", "nepal betting content",
    "nepal betting material", "nepal betting resource", "nepal betting asset",
    "nepal betting inventory", "nepal betting stock", "nepal betting supply",
    "nepal betting demand", "nepal betting market", "nepal betting industry",
    "nepal betting sector", "nepal betting field", "nepal betting domain",
    "nepal betting area", "nepal betting discipline", "nepal betting specialty",
    "nepal betting niche", "nepal betting segment", "nepal betting category",
    "nepal betting classification", "nepal betting grouping", "nepal betting clustering",
    "nepal betting categorization", "nepal betting sorting", "nepal betting filtering",
    "nepal betting searching", "nepal betting finding", "nepal betting discovery",
    "nepal betting exploration", "nepal betting investigation", "nepal betting examination",
    "nepal betting analysis", "nepal betting evaluation", "nepal betting assessment",
    "nepal betting appraisal", "nepal betting estimation", "nepal betting calculation",
    "nepal betting computation", "nepal betting measurement", "nepal betting quantification",
    "nepal betting qualification", "nepal betting characterization", "nepal betting description",
    "nepal betting explanation", "nepal betting interpretation", "nepal betting translation",
    "nepal betting transformation", "nepal betting conversion", "nepal betting adaptation",
    "nepal betting modification", "nepal betting alteration", "nepal betting adjustment",
    "nepal betting refinement", "nepal betting improvement", "nepal betting enhancement",
    "nepal betting optimization", "nepal betting maximization", "nepal betting minimization",
    "nepal betting reduction", "nepal betting elimination", "nepal betting removal",
    "nepal betting deletion", "nepal betting erasure", "nepal betting destruction",
    "nepal betting termination", "nepal betting cessation", "nepal betting discontinuation",
    "nepal betting suspension", "nepal betting interruption", "nepal betting disruption",
    "nepal betting disturbance", "nepal betting interference", "nepal betting obstruction",
    "nepal betting hindrance", "nepal betting impediment", "nepal betting barrier",
    "nepal betting obstacle", "nepal betting challenge", "nepal betting difficulty",
    "nepal betting problem", "nepal betting issue", "nepal betting concern",
    "nepal betting trouble", "nepal betting complication", "nepal betting complexity",
    "nepal betting confusion", "nepal betting uncertainty", "nepal betting doubt",
    "nepal betting hesitation", "nepal betting reluctance", "nepal betting resistance",
    "nepal betting opposition", "nepal betting objection", "nepal betting disagreement",
    "nepal betting dispute", "nepal betting conflict", "nepal betting controversy",
    "nepal betting argument", "nepal betting debate", "nepal betting discussion",
    "nepal betting negotiation", "nepal bargaining", "nepal betting mediation",
    "nepal betting arbitration", "nepal betting adjudication", "nepal betting resolution",
    "nepal betting settlement", "nepal betting agreement", "nepal betting contract",
    "nepal betting deal", "nepal betting arrangement", "nepal betting understanding",
    "nepal betting commitment", "nepal betting promise", "nepal betting pledge",
    "nepal betting guarantee", "nepal betting assurance", "nepal betting warranty",
    "nepal betting certification", "nepal betting validation", "nepal betting confirmation",
    "nepal betting verification", "nepal betting authentication", "nepal betting authorization",
    "nepal betting permission", "nepal betting consent", "nepal betting approval",
    "nepal betting endorsement", "nepal betting support", "nepal betting backing",
    "nepal betting sponsorship", "nepal betting patronage", "nepal betting funding",
    "nepal betting financing", "nepal betting investment", "nepal betting capital",
    "nepal betting resources", "nepal betting assets", "nepal betting funds",
    "nepal betting money", "nepal betting currency", "nepal betting payment",
    "nepal betting transaction", "nepal betting transfer", "nepal betting deposit",
    "nepal betting withdrawal", "nepal betting payout", "nepal betting settlement",
    "nepal betting clearance", "nepal betting reconciliation", "nepal betting balancing",
    "nepal betting accounting", "nepal booking", "nepal betting record keeping",
    "nepal betting reporting", "nepal betting disclosure", "nepal betting transparency",
    "nepal betting openness", "nepal betting honesty", "nepal betting integrity",
    "nepal betting ethics", "nepal betting morality", "nepal betting principles",
    "nepal betting values", "nepal betting standards", "nepal betting quality",
    "nepal betting excellence", "nepal betting superiority", "nepal betting distinction",
    "nepal betting uniqueness", "nepal betting originality", "nepal betting creativity",
    "nepal betting innovation", "nepal betting invention", "nepal betting discovery",
    "nepal betting exploration", "nepal betting adventure", "nepal betting journey",
    "nepal betting experience", "nepal betting story", "nepal betting narrative",
    "nepal betting tale", "nepal betting legend", "nepal betting myth",
    "nepal betting history", "nepal betting heritage", "nepal betting tradition",
    "nepal betting culture", "nepal betting society", "nepal betting community",
    "nepal betting population", "nepal betting people", "nepal betting nation",
    "nepal betting country", "nepal betting region", "nepal betting territory",
    "nepal betting area", "nepal betting zone", "nepal betting district",
    "nepal betting province", "nepal betting state", "nepal betting city",
    "nepal betting town", "nepal betting village", "nepal betting locality",
    "nepal betting neighborhood", "nepal betting vicinity", "nepal betting surroundings",
    "nepal betting environment", "nepal betting atmosphere", "nepal betting climate",
    "nepal betting weather", "nepal betting condition", "nepal betting situation",
    "nepal betting circumstance", "nepal betting context", "nepal betting background",
    "nepal betting setting", "nepal betting scene", "nepal betting stage",
    "nepal betting platform", "nepal betting arena", "nepal betting field",
    "nepal betting ground", "nepal betting pitch", "nepal betting court",
    "nepal betting track", "nepal betting course", "nepal betting route",
    "nepal betting path", "nepal betting way", "nepal betting direction",
    "nepal bearing", "nepal betting course", "nepal betting heading",
    "nepal betting bearing", "nepal betting orientation", "nepal betting position",
    "nepal betting location", "nepal betting place", "nepal betting spot",
    "nepal betting point", "nepal betting site", "nepal betting venue",
    "nepal betting destination", "nepal betting target", "nepal betting goal",
    "nepal betting objective", "nepal betting aim", "nepal betting purpose",
    "nepal betting intention", "nepal betting motive", "nepal betting reason",
    "nepal betting cause", "nepal betting justification", "nepal betting rationale",
    "nepal betting explanation", "nepal betting argument", "nepal betting defense",
    "nepal betting case", "nepal betting plea", "nepal betting appeal",
    "nepal betting request", "nepal betting petition", "nepal betting demand",
    "nepal betting claim", "nepal betting assertion", "nepal betting statement",
    "nepal betting declaration", "nepal betting proclamation", "nepal betting announcement",
    "nepal betting notification", "nepal betting alert", "nepal betting warning",
    "nepal betting caution", "nepal betting advice", "nepal betting recommendation",
    "nepal betting suggestion", "nepal betting tip", "nepal betting hint",
    "nepal betting clue", "nepal betting indication", "nepal betting sign",
    "nepal betting signal", "nepal betting message", "nepal betting communication",
    "nepal betting transmission", "nepal betting broadcast", "nepal betting publication",
    "nepal betting release", "nepal betting issue", "nepal betting edition",
    "nepal betting version", "nepal betting revision", "nepal betting update",
    "nepal betting upgrade", "nepal betting enhancement", "nepal betting improvement",
    "nepal betting development", "nepal betting progress", "nepal betting advancement",
    "nepal betting evolution", "nepal betting growth", "nepal betting expansion",
    "nepal betting extension", "nepal betting enlargement", "nepal betting increase",
    "nepal betting rise", "nepal betting climb", "nepal betting ascent",
    "nepal betting elevation", "nepal betting promotion", "nepal betting advancement",
    "nepal betting progression", "nepal betting movement", "nepal betting motion",
    "nepal betting action", "nepal betting activity", "nepal betting operation",
    "nepal betting execution", "nepal betting implementation", "nepal betting realization",
    "nepal betting achievement", "nepal betting accomplishment", "nepal betting success",
    "nepal betting victory", "nepal betting triumph", "nepal betting win",
    "nepal betting conquest", "nepal betting mastery", "nepal betting dominance",
    "nepal betting supremacy", "nepal betting leadership", "nepal betting guidance",
    "nepal betting direction", "nepal betting management", "nepal betting control",
    "nepal betting regulation", "nepal betting governance", "nepal betting oversight",
    "nepal betting supervision", "nepal betting administration", "nepal betting organization",
    "nepal betting coordination", "nepal betting arrangement", "nepal betting planning",
    "nepal betting scheduling", "nepal booking", "nepal betting reservation",
    "nepal betting appointment", "nepal booking", "nepal betting engagement",
    "nepal booking", "nepal booking", "nepal booking",
    // Nepali keywords
    "नेपालको भरोसेमान्य बुक", "कानूनी बेटिङ नेपाल", "सुरक्षित गेमिङ नेपाल",
    "निष्पक्ष खेल नेपाल", "अनलाइन बेटिङ नेपाल", "क्रिकेट बेटिङ नेपाल",
    "लाइभ क्यासिनो नेपाल", "इस्पोर्ट्स नेपाल", "PUBG टुर्नामेन्ट नेपाल",
    "नेपाल गेमिङ प्लेटफर्म", "eSewa बेटिङ", "Khalti क्यासिनो",
  ],
  authors: [{ name: "GorkhaBooks", url: "https://gorkha.com" }],
  creator: "GorkhaBooks",
  publisher: "GorkhaBooks",
  metadataBase: new URL("https://gorkha.com"),
  alternates: {
    canonical: "https://gorkha.com",
  },
  category: "Online Gaming, Sports Betting & Esports",
  openGraph: {
    type: "website",
    locale: "en_NP",
    alternateLocale: ["ne_NP"],
    url: "https://gorkha.com",
    siteName: "GorkhaBooks – Nepal's #1 Gaming Platform",
    title: "GorkhaBooks – नेपालको #१ गेमिङ, बेटिङ र इस्पोर्ट्स प्लेटफर्म | gorkha.com",
    description:
      "GorkhaBooks (gorkha.com) – Nepal's most trusted online gaming & sports betting platform. Bet on IPL Cricket & Football, play Live Casino, join PUBG & Free Fire Esports tournaments. eSewa/Khalti accepted. 50,000+ players. Join FREE via WhatsApp!",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "GorkhaBooks – नेपालको #१ ट्रस्टेड गेमिङ प्लेटफर्म | gorkha.com",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@GorkhaBooks",
    creator: "@GorkhaBooks",
    title: "GorkhaBooks Nepal – #1 Online Gaming, Betting & Esports | gorkha.com",
    description:
      "नेपालको #१ गेमिङ प्लेटफर्म। PUBG, Free Fire tournaments + Cricket/Football betting + Live Casino. 50,000+ players. Join FREE on WhatsApp!",
    images: ["/opengraph-image"],
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    // TODO: Replace with real codes from Google Search Console & Yandex Webmaster
    // google: "YOUR_GOOGLE_VERIFICATION_CODE",
    // yandex: "YOUR_YANDEX_VERIFICATION_CODE",
  },
  other: {
    "geo.region": "NP",
    "geo.placename": "Nepal",
    "geo.position": "28.3949;84.1240",
    "ICBM": "28.3949, 84.1240",
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "SportsOrganization",
  "name": "GorkhaBooks",
  "legalName": "GorkhaBooks (gorkha.com)",
  "alternateName": [
    "Gorkha Books", "GorkhaBooks Nepal", "gorkha.com",
    "Gorkha Gaming", "Gorkha Gaming Nepal", "Gorkha Esports",
    "Gorkha Online Gaming", "Nepal Gorkha Gaming", "Gorkha Gaming Platform",
    "गोर्खाबुक्स", "गोर्खा गेमिङ नेपाल"
  ],
  "url": "https://gorkha.com",
  "logo": "https://gorkha.com/logo.png",
  "image": "https://gorkha.com/opengraph-image",
  "description": "Nepal's #1 trusted, legal and licensed online gaming, sports betting, esports tournaments and live casino platform. GorkhaBooks (gorkha.com) – bet on IPL cricket and football, play live casino, join PUBG & Free Fire tournaments. Deposit via eSewa and Khalti. 50,000+ verified players.",
  "foundingDate": "2020",
  "numberOfEmployees": { "@type": "QuantitativeValue", "value": 50 },
  "areaServed": {
    "@type": "Country",
    "name": "Nepal",
    "sameAs": "https://en.wikipedia.org/wiki/Nepal",
  },
  "address": {
    "@type": "PostalAddress",
    "addressCountry": "NP",
    "addressLocality": "Kathmandu",
    "addressRegion": "Bagmati Province",
  },
  "contactPoint": [
    {
      "@type": "ContactPoint",
      "contactType": "customer support",
      "availableLanguage": ["English", "Nepali"],
      "contactOption": "TollFree",
      "hoursAvailable": "Mo-Su 00:00-23:59",
    },
    {
      "@type": "ContactPoint",
      "contactType": "sales",
      "contactOption": "TollFree",
      "availableLanguage": ["English", "Nepali"],
    }
  ],
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "4.9",
    "bestRating": "5",
    "worstRating": "1",
    "ratingCount": "12480",
    "reviewCount": "12480",
  },
  "sameAs": [
    "https://wa.link/gme782",
    "https://t.me/GorkhaBooks",
  ],
  "hasOfferCatalog": {
    "@type": "OfferCatalog",
    "name": "GorkhaBooks Games & Betting",
    "itemListElement": [
      { "@type": "Offer", "name": "Sports Betting Nepal", "description": "Bet on Cricket, Football, Kabaddi, Tennis & Esports", "priceCurrency": "NPR" },
      { "@type": "Offer", "name": "Live Casino Nepal", "description": "Teen Patti, Roulette, Blackjack, Andar Bahar & Slots", "priceCurrency": "NPR" },
      { "@type": "Offer", "name": "Esports Tournaments Nepal", "description": "PUBG, Free Fire, Valorant, BGMI tournaments", "priceCurrency": "NPR" },
      { "@type": "Offer", "name": "100% Welcome Bonus", "description": "100% match bonus up to NPR 10,000 on first deposit", "priceCurrency": "NPR" },
    ],
  },
  "paymentAccepted": "eSewa, Khalti, IME Pay, FonePay, ConnectIPS, Bank Transfer",
  "currenciesAccepted": "NPR",
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "name": "GorkhaBooks",
  "alternateName": "Gorkha Gaming Nepal",
  "url": "https://gorkha.com",
  "description": "Nepal's #1 trusted & legal online gaming, sports betting and casino platform",
  "inLanguage": ["en", "ne"],
  "potentialAction": {
    "@type": "SearchAction",
    "target": {
      "@type": "EntryPoint",
      "urlTemplate": "https://gorkha.com/blog?search={search_term_string}",
    },
    "query-input": "required name=search_term_string",
  },
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    {
      "@type": "Question",
      "name": "How do I join GorkhaBooks?",
      "acceptedAnswer": { "@type": "Answer", "text": "Join GorkhaBooks in minutes via WhatsApp. Send us a message and our team will register you instantly with a welcome bonus. नेपालको नं1‍ भरोसेमान्य बुक GorkhaBooksमा WhatsApp मार्फत जोडिनुहोस्।" },
    },
    {
      "@type": "Question",
      "name": "What payment methods does GorkhaBooks accept?",
      "acceptedAnswer": { "@type": "Answer", "text": "GorkhaBooks accepts eSewa, Khalti, IME Pay, FonePay, ConnectIPS and direct bank transfers in Nepali Rupees (NPR). नेपाली रुपियाँमा eSewa, Khalti, IME Pay मार्फत जम्मा गर्नुहोस्।" },
    },
    {
      "@type": "Question",
      "name": "How fast are withdrawals on GorkhaBooks?",
      "acceptedAnswer": { "@type": "Answer", "text": "Withdrawals on GorkhaBooks are processed within 5 minutes for amounts under NPR 50,000. GorkhaBooksमा निकासी ८ मिनेटभित्रै हुन्छ।" },
    },
    {
      "@type": "Question",
      "name": "Is GorkhaBooks safe, legal and trusted in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "Yes. GorkhaBooks is Nepal's most trusted and legal online gaming platform. It uses 256-bit SSL encryption, is trusted by 50,000+ verified players, and operates with full transparency and fairness. GorkhaBooks नेपालको सबभन्दा भरोसेमान्य र कानूनी गेमिङ प्लेटफर्म हो।" },
    },
    {
      "@type": "Question",
      "name": "What sports can I bet on at GorkhaBooks?",
      "acceptedAnswer": { "@type": "Answer", "text": "You can bet on Cricket (IPL, World Cup, Nepal T20), Football (Premier League, Champions League), Kabaddi, Tennis, Esports (PUBG, Free Fire, BGMI) and more. क्रिकेट, फुटबल, कबड्डी, इस्पोर्ट्समा बेट लगाउनुहोस्।" },
    },
    {
      "@type": "Question",
      "name": "GorkhaBooks कसरी जोडिने?",
      "acceptedAnswer": { "@type": "Answer", "text": "GorkhaBooksमा जोडिन WhatsAppमा मेसेज गर्नुहोस्। हाम्रो टिमले तुरन्त दर्ता गरिदिन्छ र वेलकम बोनस पनि दिन्छ। नेपालको नं1‍ गेमिङ प्लेटफर्म।" },
    },
    {
      "@type": "Question",
      "name": "Nepal ma online betting legal cha?",
      "acceptedAnswer": { "@type": "Answer", "text": "GorkhaBooks is a fully legal and licensed gaming platform operating in Nepal. We follow all applicable regulations and are committed to responsible, transparent and fair gaming for all Nepali players." },
    },
    {
      "@type": "Question",
      "name": "Does GorkhaBooks have a welcome bonus?",
      "acceptedAnswer": { "@type": "Answer", "text": "Yes! GorkhaBooks offers a 100% Welcome Bonus up to NPR 10,000 on your first deposit, plus weekly cashback, referral bonuses and VIP rewards. Join via WhatsApp to claim instantly." },
    },
    {
      "@type": "Question",
      "name": "Which is the best betting site in Nepal 2026?",
      "acceptedAnswer": { "@type": "Answer", "text": "GorkhaBooks is Nepal's best betting site in 2026. It offers the highest odds, fastest payouts (5 minutes), eSewa & Khalti deposits, 100% welcome bonus, live casino, cricket & football betting, and 24/7 Nepali customer support. Trusted by 50,000+ verified players." },
    },
    {
      "@type": "Question",
      "name": "Can I bet using eSewa or Khalti in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "Yes. GorkhaBooks fully supports eSewa, Khalti and IME Pay for both deposits and withdrawals. Simply deposit from your eSewa or Khalti wallet in seconds – no bank account needed. Minimum deposit is NPR 100." },
    },
    {
      "@type": "Question",
      "name": "How fast are withdrawals at GorkhaBooks Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "GorkhaBooks processes withdrawals in under 5 minutes via eSewa, Khalti and IME Pay. Same-day withdrawal is guaranteed for all verified accounts. It is the fastest withdrawal betting site in Nepal." },
    },
    {
      "@type": "Question",
      "name": "How do I start online betting in Nepal for the first time?",
      "acceptedAnswer": { "@type": "Answer", "text": "Starting online betting in Nepal is easy with GorkhaBooks: 1) Message us on WhatsApp, 2) Get registered instantly, 3) Deposit via eSewa or Khalti (min NPR 100), 4) Claim your 100% welcome bonus, 5) Place your first bet on cricket, football or casino games. You can start with just NPR 500." },
    },
    {
      "@type": "Question",
      "name": "How to play Aviator game in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "Aviator is a crash game available on GorkhaBooks. Place your bet before the plane takes off, then cash out before it flies away. The longer you wait, the higher the multiplier – but cash out before the crash! Play Aviator with real money using eSewa or Khalti on GorkhaBooks." },
    },
    {
      "@type": "Question",
      "name": "What is the minimum deposit for online betting in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "The minimum deposit at GorkhaBooks is NPR 100 via eSewa, Khalti or IME Pay. There is no minimum withdrawal limit. You can start betting in Nepal with as little as NPR 100 and get a 100% welcome bonus on your first deposit." },
    },
    {
      "@type": "Question",
      "name": "IPL 2026 betting Nepal – how to bet on IPL?",
      "acceptedAnswer": { "@type": "Answer", "text": "Bet on IPL 2026 at GorkhaBooks: choose your match, pick your market (match winner, top batsman, total runs etc.), enter your stake and confirm. IPL betting is available live with real-time odds. Deposit via eSewa or Khalti and get your winnings within 5 minutes." },
    },
    {
      "@type": "Question",
      "name": "Is betting legal in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "GorkhaBooks operates as a legal and licensed gaming platform in Nepal. We comply with all applicable regulations and provide a safe, transparent betting environment for Nepali players. Online sports betting and casino gaming through licensed platforms like GorkhaBooks is permitted." },
    },
    {
      "@type": "Question",
      "name": "Is online betting allowed in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "Yes, online betting through licensed platforms like GorkhaBooks is allowed in Nepal. GorkhaBooks is fully licensed and offers legal online sports betting, cricket, football, casino games and esports to Nepali players aged 18+." },
    },
    {
      "@type": "Question",
      "name": "Is gambling legal in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "GorkhaBooks is a legally licensed online gaming and betting platform operating in Nepal. We offer sports betting, live casino and esports games in full compliance with Nepal's gaming regulations. Players must be 18+ to participate." },
    },
    {
      "@type": "Question",
      "name": "How does betting work in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "Betting in Nepal with GorkhaBooks is simple: 1) Register via WhatsApp, 2) Deposit using eSewa, Khalti or IME Pay, 3) Choose your sport or casino game, 4) Select your odds or bet type, 5) Enter stake and confirm. Winnings are withdrawn within 5 minutes to your wallet." },
    },
    {
      "@type": "Question",
      "name": "What is the legal age for betting in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "The legal age for betting in Nepal is 18 years and above. GorkhaBooks strictly enforces age verification and does not allow betting by minors. All players must verify their age and identity before placing bets." },
    },
    {
      "@type": "Question",
      "name": "Can Nepalese use international betting sites?",
      "acceptedAnswer": { "@type": "Answer", "text": "While some international sites may accept Nepali players, GorkhaBooks is the best choice for Nepal. We offer Nepal-specific features like eSewa/Khalti deposits, NPR currency, local cricket/football betting, 24/7 Nepali support, and instant payouts – which international sites often lack." },
    },
    {
      "@type": "Question",
      "name": "How to register on a betting site in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "Register on GorkhaBooks in seconds via WhatsApp. Simply message us, provide your name and phone number, and our team will create your account instantly. No lengthy forms or documents required. You'll receive your welcome bonus immediately after your first deposit." },
    },
    {
      "@type": "Question",
      "name": "How to deposit money for betting in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "Deposit on GorkhaBooks using eSewa, Khalti or IME Pay. Minimum deposit is NPR 100. Simply go to your account, select deposit, choose your wallet, enter the amount and confirm. Funds are credited instantly. Bank transfer is also available for larger deposits." },
    },
    {
      "@type": "Question",
      "name": "How to withdraw betting winnings in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "Withdraw your winnings from GorkhaBooks to eSewa, Khalti or IME Pay within 5 minutes. Go to withdrawal, select your wallet, enter amount and confirm. No withdrawal fees for amounts above NPR 500. Same-day withdrawal guaranteed for all verified accounts." },
    },
    {
      "@type": "Question",
      "name": "Is sports betting taxed in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "GorkhaBooks handles all applicable taxes and compliance. Players receive their winnings without tax deductions at the time of withdrawal. For large winnings, we recommend consulting a local tax advisor for personal tax obligations in Nepal." },
    },
    {
      "@type": "Question",
      "name": "Which betting sites are available in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "GorkhaBooks is Nepal's #1 trusted betting site. Other options include MelBet, 1xBet, Parimatch and 22bet, but GorkhaBooks offers the best for Nepali players: eSewa/Khalti deposits, NPR currency, local cricket/football betting, instant 5-minute withdrawals, and 24/7 Nepali customer support." },
    },
    {
      "@type": "Question",
      "name": "Which betting sites accept Nepalese players?",
      "acceptedAnswer": { "@type": "Answer", "text": "GorkhaBooks is built specifically for Nepali players and accepts all Nepali users. We accept eSewa, Khalti and IME Pay, operate in NPR currency, and offer Nepal-specific sports like IPL, Nepal Premier League, and local cricket/football betting. Join via WhatsApp for instant registration." },
    },
    {
      "@type": "Question",
      "name": "What is the best betting strategy for Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "The best betting strategy for Nepal includes: 1) Start with small bets (NPR 100-500), 2) Focus on sports you know well like IPL cricket, 3) Use value betting on underdog teams, 4) Take advantage of the 100% welcome bonus, 5) Set a betting budget and stick to it, 6) Cash out winnings regularly. GorkhaBooks offers expert tips daily on our blog." },
    },
    {
      "@type": "Question",
      "name": "How to win at sports betting in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "To win at sports betting in Nepal: 1) Research teams and players before betting, 2) Follow expert predictions on GorkhaBooks blog, 3) Bet on sports you understand (cricket, football), 4) Use accumulator bets for higher odds, 5) Manage your bankroll wisely, 6) Take advantage of live betting opportunities, 7) Use the cash out feature to secure profits." },
    },
    {
      "@type": "Question",
      "name": "What is handicap betting in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "Handicap betting in Nepal gives one team a virtual advantage or disadvantage to level the playing field. For example, if Nepal gets +1.5 goals against India, Nepal wins the bet even if they draw or lose by 1 goal. GorkhaBooks offers handicap betting on cricket, football and other sports with competitive odds." },
    },
    {
      "@type": "Question",
      "name": "What is accumulator betting in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "Accumulator betting (also called parlay) combines multiple bets into one. All selections must win for the bet to succeed, but the odds multiply together for higher payouts. For example, combining 3 cricket matches at 2.0 odds each gives 8.0 total odds. GorkhaBooks offers accumulator betting on all sports with accumulator bonuses." },
    },
    {
      "@type": "Question",
      "name": "What is over/under betting in Nepal?",
      "acceptedAnswer": { "@type": "Answer", "text": "Over/under betting in Nepal lets you bet on whether the total score in a match will be over or under a set number. For example, betting 'over 3.5 goals' in football means you win if 4 or more goals are scored. GorkhaBooks offers over/under betting on cricket (runs), football (goals), basketball (points) and more." },
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`} suppressHydrationWarning>
      <head suppressHydrationWarning>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />
        <meta name="theme-color" content="#03040a" />
        <meta name="msapplication-TileColor" content="#03040a" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
        />
      </head>
      <body className="min-h-full flex flex-col bg-[#03040a] text-white" suppressHydrationWarning>
        <AutoRedirect />
        <ScrollProgress />
        <Navbar />
        <TrustBar />
        <main className="flex-1 pt-7">{children}</main>
        <Footer />
        <FloatingWhatsApp />
        <NotificationPopup />
        <MobileBottomCTA />
      </body>
    </html>
  );
}
